version: '3.4'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      - "discovery.type=single-node"
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - engine.labels.purpose == elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: manager1
      ELASTICSEARCH_URL: http://elastic1:9200
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager

volumes:
  elastic-data: