version: '3.6'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: manager1
      ELASTICSEARCH_URL: http://elastic1:9200
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
