version: '3.4'
services:
  registry_mirror:
    image: registry:2.6.2
    ports: 
      - "5000:5000/tcp"
    volumes:
      - mirror:/var/lib/registry
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
    deploy:
      replicas: 1

  private_registry:
    image: registry:2.6.2
    ports: 
      - "80:5000/tcp"
    volumes:
      - insecurereg:/var/lib/registry
    deploy:
      replicas: 1

volumes:
  mirror:
    driver: local
  insecurereg:
    driver: local