version: '3.3'
services:
  registryMirror:
    image: registry:latest
    ports: 
      - "5000:5000/tcp"
    volumes:
      - mirror:/var/lib/registry
    # environment:
    #   - REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io"
    #   - USERNAME=farscapian
    #   - PASSWORD=2OIS5bJ2O6NHbjmuhG
        # - STORAGE_PATH=/registry
        # - STANDALONE=false 
        # - MIRROR_SOURCE=https://registry-1.docker.io 
        # - MIRROR_SOURCE_INDEX=https://index.docker.io
    deploy:
      mode: replicated
      replicas: 1
    configs:
      - source: registry-mirror-config  #TODO check file permissions to least prviliege
        target: /etc/docker/registry/config.yml
        uid: '33'
        gid: '33'
        mode: 0640

  # insecureRegistry:
  #   image: registry:latest
  #   ports: 
  #     - "5001:5000/tcp"
  #   volumes:
  #     - insecurereg:/var/lib/registry
  #   deploy:
  #     mode: replicated
  #     replicas: 1

volumes:
  mirror: 
  insecurereg:


configs:
  registry-mirror-config:
    file: ./mirror.config.yml

